/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./App.{js,jsx,ts,tsx}",
    "./components/Header/Header.{js,jsx,ts,tsx}",
    "./components/Header/HeaderForDH.{js,jsx,ts,tsx}",
    "./components/Header/HeaderForProfile.{js,jsx,ts,tsx}",
    "./components/Header/HeaderForStack.{js,jsx,ts,tsx}",
    "./components/Navbar.{js,jsx,ts,tsx}",
    "./screens/Home.{js,jsx,ts,tsx}",
    "./screens/Offer.{js,jsx,ts,tsx}",
    "./screens/Support.{js,jsx,ts,tsx}",
    "./screens/Order.{js,jsx,ts,tsx}",
    "./screens/Profile.{js,jsx,ts,tsx}",
    "./screens/FeeCal.{js,jsx,ts,tsx}",
    "./screens/Service.{js,jsx,ts,tsx}",
    "./screens/CheckPost.{js,jsx,ts,tsx}",
    "./components/Navbar/RouteManager.{js,jsx,ts,tsx}",
    "./components/Home/SearchBar.{js,jsx,ts,tsx}",
    "./components/Home/ServiceBtn.{js,jsx,ts,tsx}",
    "./components/Home/News.{js,jsx,ts,tsx}",
    "./components/Home/Slider.{js,jsx,ts,tsx}",
    "./components/Offer/OfferContent.{js,jsx,ts,tsx}",
    "./components/Support/FastBtn.{js,jsx,ts,tsx}",
    "./components/Support/SupportRequest.{js,jsx,ts,tsx}",
    "./components/Order/OrderItem.{js,jsx,ts,tsx}",
    "./components/Order/SenderOrder.{js,jsx,ts,tsx}",
    "./components/Order/ReceiverOrder.{js,jsx,ts,tsx}",
    "./components/Input/DropdownInput.{js,jsx,ts,tsx}",
    "./components/Input/EnterInput.{js,jsx,ts,tsx}",
    "./components/Input/Checkbox.{js,jsx,ts,tsx}",
    "./components/Buttons/Button.{js,jsx,ts,tsx}",
    "./components/Buttons/ServiceBtn.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};
